### PR TITLE
fix: update lucia adder

### LINKED ISSUE #122: lucia: add `setSessionTokenCookie` and `deleteSessionTokenCookie` methods
It would help following the guide to have `setSessionTokenCookie` and `deleteSessionTokenCookie` methods:
https://github.com/lucia-auth/example-sveltekit-email-password-2fa/blob/main/src/lib/server/session.ts#L57

### PR DESCRIPTION
**Pull request by pilcrowonpaper**
- Adds `setSessionTokenCookie()` and `deleteSessionTokenCookie()` (closes #122)
- Fixes sessions to be consistent with lucia-auth.com. This isn't a security issue, but the hashing part wasn't implement properly which negated the benefits it provided.
- Update `generateUserId()` to be consistent with `generateSessionToken()` and easier to deal with.
- Removed return types to be consistent with the rest of the codebase.

I haven't added change sets yet and I'm not sure how to test the adder.

### CODE REVIEW

File: packages/adders/lucia/index.ts [hunk 1]
```diff
@@ -217,6 +217,9 @@ export default defineAdder({
 				});
 				imports.addNamed(ast, '@oslojs/crypto/sha2', { sha256: 'sha256' });
 				imports.addNamed(ast, 'drizzle-orm', { eq: 'eq' });
+				if (typescript) {
```
Comment (pilcrowonpaper) [inline packages/adders/lucia/index.ts:220]: I'm not sure if this is the correct way to add type imports

**Comment by manuel3108** [comment]
Cool, thanks!

You can test the adder by running `pnpm sv add lucia` insider the `pnpm workspace`. 
Or use `pnpx https://pkg.pr.new/sveltejs/cli/sv@254 add lucia` which was published instants ago

File: packages/adders/lucia/index.ts [hunk 2]
```diff
@@ -365,7 +392,7 @@ export default defineAdder({
 				const [ts] = utils.createPrinter(typescript);
 				return dedent`
 					import { hash, verify } from '@node-rs/argon2';
-					import { generateRandomString } from '@oslojs/crypto/random';
+					import { encodeBase32LowerCaseNoPadding } from '@oslojs/encoding';
```
Comment (benmccann) [inline packages/adders/lucia/index.ts:395]: thanks! are there some docs where I can learn more about this method and others that are available? I didn't see it mentioned on https://oslo.js.org/reference/encoding/

Comment (pilcrowonpaper) [reply packages/adders/lucia/index.ts:395]: Sorry, that's the "v1" docs. The "v2" successor is available at https://encoding.oslojs.dev and it's documented here

https://encoding.oslojs.dev/reference/main/encodeBase32LowerCaseNoPadding

Comment (pilcrowonpaper) [reply packages/adders/lucia/index.ts:395]: Base32 is much more compact than hex encoding (used by UUID etc) but it's also case insensitive and doesn't use special characters unlike base64

File: packages/adders/lucia/index.ts [hunk 3]
```diff
@@ -300,14 +294,47 @@ export default defineAdder({
...
+				}
+				if (!ms.original.includes('export function deleteSessionTokenCookie')) {
+					const deleteSessionTokenCookie = dedent`					
+						${ts('', '/** @param {import("@sveltejs/kit").RequestEvent} event */')}
+						export function deleteSessionTokenCookie(event${ts(': RequestEvent')}, token${ts(': string')}, expiresAt${ts(': Date')}) {
+							event.cookies.set(sessionCookieName, '', {
+								expires: expiresAt,
+								path: '/'
+							});
+						}`;
```
Comment (AdrianGonz97) [inline packages/adders/lucia/index.ts:335]: any particular reason to use `event.cookies.set` over `event.cookies.delete`?
```suggestion
						export function deleteSessionTokenCookie(event${ts(': RequestEvent')}, expiresAt${ts(': Date')}) {
							event.cookies.delete(sessionCookieName, { path: '/' });
						}`;
```

File: packages/adders/lucia/index.ts (hunk 1 above)
Comment (AdrianGonz97) [reply packages/adders/lucia/index.ts:220]: this is good 👍

File: packages/adders/lucia/index.ts (hunk 3 above)
Comment (pilcrowonpaper) [reply packages/adders/lucia/index.ts]: Should be fixed now

File: packages/adders/lucia/index.ts [hunk 4]
```diff
@@ -229,19 +232,20 @@ export default defineAdder({
 				}
 				if (!ms.original.includes('function generateSessionToken')) {
 					const generateSessionToken = dedent`					
-						${ts('', '/** @returns {string} */')}
-						function generateSessionToken()${ts(': string')} {
+						function generateSessionToken() {
```
Comment (AdrianGonz97) [inline packages/adders/lucia/index.ts]:
```suggestion
						export function generateSessionToken() {
```

**Comment by pilcrowonpaper** [comment]
The generated TypeScript code works. I can't seem to get `sv` to generate JSDoc code tho. Is this expected?

File: packages/adders/lucia/index.ts (hunk 4 above)
Comment (pilcrowonpaper) [reply packages/adders/lucia/index.ts]: Just fixed this as well

**Comment by AdrianGonz97** [comment]
That's expected. The JSDoc in this instance is only included when `typescript` isn't present in the project.

**Comment by pilcrowonpaper** [comment]
Tested out with the published package and all the types seems to be working in both the TS and JSDoc version

**Review by AdrianGonz97 — APPROVED** [review]
much appreciated!

**Review by manuel3108 — APPROVED** [review]
Any reason this is still a draft?

File: packages/adders/lucia/index.ts (hunk 2 above)
Comment (benmccann) [reply packages/adders/lucia/index.ts:393]: I would lean towards the base 64 version to maintain the previous behavior as it's a much more compact representation and more closely matches popular implementations like https://github.com/ai/nanoid

Comment (pilcrowonpaper) [reply packages/adders/lucia/index.ts:393]: I personally prefer IDs that don't contain special characters and this provides about the same entropy as nanoid with a similar number of characters (24 vs 21). I don't mind changing it though. Do you want me to change `generateSessionToken()` to use base64 as well?

Comment (benmccann) [reply packages/adders/lucia/index.ts:393]: Yeah, I guess it makes sense to remain consistent

I see the input was changed to 15 characters. How do we know how many characters the output will be?

Comment (pilcrowonpaper) [reply packages/adders/lucia/index.ts:393]: The generated ID will actually be 24 characters. In base32, every 5 bits (that's where the 32 comes from) are converted to a corresponding character (e.g. 0b00001 => A). So you get 8 characters for every 5 bytes, or 24 characters for a 15 byte input.

For base64, it's 6 bits instead of 5, so you get 4 characters for every 3 bytes.

**Comment by benmccann** [comment]
thank you!! this is a big help

we're hoping to add more things like oauth in the future. we're working on cleaning up some of our APIs to hopefully make it easier to add and maintain add-ons.

really appreciate you taking a look!
