### PR TITLE
fix: quotes in `cd` output if necessary

### LINKED ISSUE #196: a minor issue in `create-svelte` package: instruction missing quotes in CLI output
### Describe the bug

when someone is a creating a new project by using the CLI tool, i.e. `create-svelte` package, they run `npm create svelte@latest my-app` and then the CLI guides them to create the project.

However, if the project name contains spaces (e.g. `my project`), the CLI does not wrap the project name in double quotes, like this:
```
 Next steps:
  1: cd my project
  2: npm install
  3: git init && git add -A && git commit -m "Initial commit" (optional)
  4: npm run dev -- --open
```

causing the following issue in shells like bash

```
bash: cd: too many arguments
```

### Reproduction

1. Run `npm create svelte@latest "my project"`.
2. Notice that in the generated steps, the first step is written as:
   ```
   cd my project
   ```
3. Attempting to run this command in bash results in an error.

### Logs

```Shell
bash: cd: too many arguments
```

### System Info

```Shell
npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"

  System:
    OS: Linux 6.6 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Memory: 7.91 GB / 15.51 GB
    Container: Yes
    Shell: 5.2.26 - /bin/bash
  Binaries:
    Node: 18.18.2 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.7.0 - /usr/bin/npm
  Browsers:
    Brave Browser: 125.1.66.115
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by manuel3108**
Closes #196

### CODE REVIEW

File: packages/cli/commands/create.ts [hunk 1]
```diff
@@ -51,7 +51,10 @@ export const create = new Command('create')
 			const relative = path.relative(process.cwd(), directory);
 			const pm = packageManager ?? detectSync({ cwd })?.name ?? common.getUserAgent() ?? 'npm';
 			if (relative !== '') {
-				initialSteps.push(`${i++}: ${highlight(`cd ${relative}`)}`);
+				const pathWithSpaces = relative.includes(' ');
```
Comment (benmccann) [inline packages/cli/commands/create.ts:54]:
```suggestion
				const pathHasSpaces = relative.includes(' ');
```

File: packages/cli/commands/create.ts [hunk 2]
```diff
@@ -51,7 +51,10 @@ export const create = new Command('create')
...
+				initialSteps.push(
+					`${i++}: ${highlight(`cd ${pathWithSpaces ? `"${relative}"` : relative}`)}`
```
Comment (benmccann) [inline packages/cli/commands/create.ts:56]:
```suggestion
				const pathHasSpaces = relative.includes(' ');
				initialSteps.push(
					`${i++}: ${highlight(`cd ${pathHasSpaces ? `"${relative}"` : relative}`)}`
```

**Review by benmccann — APPROVED** [review]
