### PR TITLE
fix: forward exit code of external package commands

### LINKED ISSUE #411: `sv check` always returns exit code 0
Even when there are errors. Replacing `svelte-check` with `sv check` will cause the CI to always pass.

### PR DESCRIPTION
**Pull request by rChaoz**
Closes #411

### CODE REVIEW

File: packages/cli/commands/check.ts [hunk 1]
```diff
@@ -42,5 +42,17 @@ function runCheck(cwd: string, args: string[]) {
 	try {
 		const cmd = resolveCommand(pm, 'execute-local', ['svelte-check', ...args])!;
 		execSync(`${cmd.command} ${cmd.args.join(' ')}`, { stdio: 'inherit', cwd });
-	} catch {}
+	} catch (error) {
+		// TypeScript lore
```
Comment (benmccann) [inline packages/cli/commands/check.ts:46]:
```suggestion
```

Comment (rChaoz) [reply packages/cli/commands/check.ts:46]: Yep, sorry.

**Comment by rChaoz** [comment]
@benmccann should be all good

**Review by benmccann — APPROVED** [review]

File: .changeset/proud-apples-watch.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'sv': minor
```
Comment (benmccann) [inline .changeset/proud-apples-watch.md:2]:
```suggestion
'sv': patch
```

**Comment by benmccann** [comment]
Thank you!!
