### PR TITLE
fix(cli): `dependencyVersion` is now well managed in `sv create`

### LINKED ISSUE #813: Error during library creation
Logs
```
&  pnpx sv create
Packages: +1
+
Progress: resolved 1, reused 0, downloaded 1, added 1, done

┌  Welcome to the Svelte CLI! (v0.10.2)
│
◇  Where would you like your project to be created?
│  package
│
◇  Which template would you like?
│  Svelte library
│
◇  Add type checking with TypeScript?
│  Yes, using TypeScript syntax
│
◇  What would you like to add to your project? (use arrow keys / space bar)
│  prettier, eslint, vitest, playwright, tailwindcss, devtools-json
│
◇  vitest: What do you want to use vitest for?
│  unit testing, component testing
│
◇  tailwindcss: Which plugins would you like to add?
│  none
│
◆  Project created
│
■  Error: Unable to process 'src/routes/+layout.svelte'. Reason: Failed to determine svelte version
│      at Object.file (file:///home/roman/.cache/pnpm/dlx/bb91ced9f175c6162bb1b69caa235e3593a52dcc12971190d18d5f1080773fae/19aacec033c-160e21/node_modules/.pnpm/sv@0.10.2/node_modules/sv/dist/install-DGNvl1vK.js:3111:35)
│      at Object.run (file:///home/roman/.cache/pnpm/dlx/bb91ced9f175c6162bb1b69caa235e3593a52dcc12971190d18d5f1080773fae/19aacec033c-160e21/node_modules/.pnpm/sv@0.10.2/node_modules/sv/dist/install-DGNvl1vK.js:2708:7)
│      at runAddon (file:///home/roman/.cache/pnpm/dlx/bb91ced9f175c6162bb1b69caa235e3593a52dcc12971190d18d5f1080773fae/19aacec033c-160e21/node_modules/.pnpm/sv@0.10.2/node_modules/sv/dist/install-DGNvl1vK.js:3153:14)
│      at applyAddons (file:///home/roman/.cache/pnpm/dlx/bb91ced9f175c6162bb1b69caa235e3593a52dcc12971190d18d5f1080773fae/19aacec033c-160e21/node_modules/.pnpm/sv@0.10.2/node_modules/sv/dist/install-DGNvl1vK.js:3058:59)
│      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
│      at async runAddonsApply (file:///home/roman/.cache/pnpm/dlx/bb91ced9f175c6162bb1b69caa235e3593a52dcc12971190d18d5f1080773fae/19aacec033c-160e21/node_modules/.pnpm/sv@0.10.2/node_modules/sv/dist/bin.js:993:59)
│      at async createProject (file:///home/roman/.cache/pnpm/dlx/bb91ced9f175c6162bb1b69caa235e3593a52dcc12971190d18d5f1080773fae/19aacec033c-160e21/node_modules/.pnpm/sv@0.10.2/node_modules/sv/dist/bin.js:1556:63)
│      at async file:///home/roman/.cache/pnpm/dlx/bb91ced9f175c6162bb1b69caa235e3593a52dcc12971190d18d5f1080773fae/19aacec033c-160e21/node_modules/.pnpm/sv@0.10.2/node_modules/sv/dist/bin.js:1418:57
│      at async runCommand (file:///home/roman/.cache/pnpm/dlx/bb91ced9f175c6162bb1b69caa235e3593a52dcc12971190d18d5f1080773fae/19aacec033c-160e21/node_modules/.pnpm/sv@0.10.2/node_modules/sv/dist/bin.js:502:3)
│
└  Operation failed.
```
File `src/routes/+layout.svelte` was not created

## System info

```
  System:
    OS: Linux 6.12 cpe:/o:nixos:nixos:25.05 25.05 (Warbler)
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 3.18 GB / 15.56 GB
    Container: Yes
    Shell: 5.2.37 - /run/current-system/sw/bin/bash
  Binaries:
    Node: 24.11.0 - /nix/store/4grir7s1ls3cbqp8dl91r1w8yz34zw6x-nodejs-24.11.0/bin/node
    npm: 11.6.1 - /nix/store/4grir7s1ls3cbqp8dl91r1w8yz34zw6x-nodejs-24.11.0/bin/npm
    pnpm: 10.22.0 - /nix/store/lalvgz06zbpb1hw43nr7lj8rb05k3yka-pnpm-10.22.0/bin/pnpm
  Browsers:
    Brave Browser: 141.1.83.118
```

### PR DESCRIPTION
**Pull request by jycouet**
Closes #813

### CODE REVIEW

File: packages/cli/commands/create.ts [hunk 1]
```diff
@@ -373,12 +377,20 @@ export async function createVirtualWorkspace({
 		};
 	}
 
+	// Let's read the package.json of the template we will use and add the dependencies to the override
+	const templatePackageJsonPath = dist(`templates/${template}`);
+	const { data: packageJson } = getPackageJson(templatePackageJsonPath);
+	override.dependencies = {
+		...packageJson.devDependencies,
+		...packageJson.dependencies,
+		...override.dependencies
```
Comment (manuel3108) [inline packages/cli/commands/create.ts:386]:
```suggestion
		...override.dependencies,
		...override.devDependencies
```
I don't think it makes a difference currently, but i think it would make sense for the sake of completeness.

File: .changeset/swift-dingos-boil.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'sv': patch
+---
+
+fix(cli): `dependencyVersion` is now well managed in `sv create`
```
Comment (manuel3108) [inline .changeset/swift-dingos-boil.md]:
```suggestion
fix(cli): `dependencyVersion` is now properly populated during `sv create`
```
I hope that's what you wanted to say. I couldn't imagine what the message should mean without looking at the source code.

File: packages/cli/commands/create.ts (hunk 1 above)
Comment (jycouet) [reply packages/cli/commands/create.ts:386]: To put `devDep` as a priority over `dep` ?

I set the same order as here: https://github.com/sveltejs/cli/blob/0657c618821cafea87b79624037b06a2013e08d2/packages/cli/commands/add/workspace.ts#L56-L60

And I think it's a "better" order. But you maybe have an idea in mind?

Comment (manuel3108) [reply packages/cli/commands/create.ts:386]: Just forget what I said, I cant read!
